### ISSUE TITLE
CI glue script

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri-regression#12]
We should have a script that will be invoked by the CI and will clone both repos by BuildKite and take the regression test repo config (.yml) file and invoke and cluster script that is part TITB. 

Once returned, we need to check for error conditions and if we fail, the whole test run fails. Otherwise TITB outputs another .yml that will be dropped into the iri-regression repo and this will be use for starting up ALOE. 

- [x] Define structure that we want in the output .yml file

Structure of the .yml file: https://github.com/iotaledger/iri-regression/issues/5

Structure of the output yml file:

```
defaults:
- db: https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/dev/testnet_files.tgz
- db_checksum: 6eaa06d5442416b7b8139e337a1598d2bae6a7f55c2d9d01f8c5dac69c004f75
revision_hash: 13aafa4c8ee2ffcf5f084c7bbbe8332c3d6c306e
seeds:
- SEED
- SIID
nodes:
  nodeA:
    db: https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/dev/testnet_files.tgz
    db_checksum: 6eaa06d5442416b7b8139e337a1598d2bae6a7f55c2d9d01f8c5dac69c004f75
    host: 172.20.51.96
    log: "--2018-07-21 11:52:52--  https://s3.eu-central-1.amazonaws.com/iotaledger-dbfiles/dev/testnet_files.tgz\n\
      Resolving s3.eu-central-1.amazonaws.com (s3.eu-central-1.amazonaws.com)... 52.219.74.48\n\
      \ Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed\
      \ from #0 to #8412\n07/21 11:53:04.104 [Solid Milestone Tracker] INFO  com.iota.iri.Milestone\
      \ - Latest SOLID SUBTANGLE milestone has changed from #152 to #8412\n07/21 11:53:05.992\
      \ [pool-5-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast\
      \ = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 16833\n"
    podname: iri-13aafa4c8ee2ffcf5f084c7bbbe8332c3d6c306e-nodec-5d4qc
    servicename: iri-13aafa4c8ee2ffcf5f084c7bbbe8332c3d6c306e-nodec-j8f66
    status: Running
    ports:
      api: 30090
      gossip-tcp: 32646
      gossip-udp: 32091
      jmx-prometheus: 31073
      jprofiler: 31485
      zmq-feed: 30477
```

**E: 5**
