### ISSUE TITLE
Yaml File Loading

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri-regression#5]
*Description*
Inside each `machine[x]` folder there should be a `config.yml` file.
It will be of the form:
```
defaults: &default_paths
   db: <path to db tar> #can be empty - then node starts with empty db
   db_checksum: <file digest> #can be empty

seeds: # For internal use by the regression system. 
  - <Seed 1> 
  - <Seed 2>

nodes:
  nodeA: #name
    #Inherit default vals 
    <<: *default_paths

  nodeB: #name
    #Inherit default vals
    <<: *default_paths

  nodeC: #name
    #Input custom db and snapshot paths 
    db: <path to 2nd db tar> #can be empty 
    db_checksum: <file digest> #can be empty 

#And so on 
```

It will give instructions to TIT(S)B how to set up the nodes in the machine it is running on. Currently we assume that the nodes will be running on different addresses with the `--testnet`.

We need to parse it and save a global dictionary of of node_name:host.

*Requirements*:

1. In the world global environment, save a mapping between the node’s name to the host.
2. In the world global environment, save the seeds.

**E: 3**
